FROM ubuntu:20.04

RUN apt-get update
RUN apt-get upgrade --yes
RUN apt install cmake --yes
RUN apt install curl --yes
RUN apt install wget
RUN apt-get install git make --yes
RUN apt-get install python3 python3-pip --yes

# Installing OCaml
#   - opam v2.0.5
#   - OCaml v5.0.0
#   - dune v3.10.0
#   - menhir v20230608

RUN apt-get install opam libgmp-dev --yes
RUN opam init --disable-sandboxing
RUN opam switch create 5.0.0
RUN opam install dune menhir zarith --yes
RUN eval $(opam config env)


WORKDIR /home


# Install wabt

RUN git clone --recursive https://github.com/WebAssembly/wabt && \
    cd wabt && \
    git submodule update --init


# Build wabt

RUN mkdir wabt/build && cd wabt/build && cmake .. && cmake --build .
ENV PATH="${PATH}:/home/wabt/bin"


# Install spectec

RUN git clone https://github.com/kaist-plrg/spectec.git


# Checkout to west

WORKDIR /home/spectec/spectec
RUN git checkout west


# Install wasmer

RUN curl https://get.wasmer.io -sSfL | sh
ENV WASMER_DIR="/root/.wasmer"
ENV WASMER_CACHE_DIR="$WASMER_DIR/cache"
ENV PATH="${PATH}:$WASMER_DIR/bin"


# Install wasmtime

RUN curl https://wasmtime.dev/install.sh -sSf | bash


# Install wasm3

WORKDIR /home
RUN git clone https://github.com/wasm3/wasm3.git
RUN mkdir -p /home/wasm3/build
WORKDIR /home/wasm3/build
RUN cmake ..
RUN make -j8
RUN cp /home/wasm3/build/wasm3 /home/spectec/spectec/runtimes/wasm3
WORKDIR /home/spectec/spectec/runtimes/wasm3
# RUN wget https://github.com/wasm3/wasm3/releases/download/v0.5.0/wasm3-linux-x64.elf
# RUN mv wasm3-linux-x64.elf wasm3
RUN chmod +x wasm3
# TODO


# Install wasmedge

WORKDIR /home/spectec/spectec/runtimes/wasmedge
RUN curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -p .
RUN /bin/bash -c "source ./env && make"
# TODO


WORKDIR /home/spectec/spectec


# Automate `eval $(opam env)`

ENTRYPOINT ["opam", "exec", "--"]
CMD ["/bin/bash", "--login"]
