FROM ubuntu:20.04

RUN apt-get update
RUN apt-get upgrade --yes
RUN apt-get install git make curl --yes


# Installing OCaml
#   - opam v2.0.5
#   - OCaml v5.0.0
#   - dune v3.10.0
#   - menhir v20230608

RUN apt-get install opam --yes
RUN opam init --disable-sandboxing
RUN opam switch create 5.0.0
RUN opam install dune menhir --yes
RUN eval $(opam config env)


# Install wasmer

RUN curl https://get.wasmer.io -sSfL | sh
ENV WASMER_DIR="/root/.wasmer"
ENV WASMER_CACHE_DIR="$WASMER_DIR/cache"
ENV PATH="${PATH}:$WASMER_DIR/bin"


# Install wasmtime

RUN curl https://wasmtime.dev/install.sh -sSf | bash


# Install spectec

WORKDIR /home
RUN git clone https://github.com/kaist-plrg/spectec.git


# Checkout to lww

WORKDIR /home/spectec/spectec
RUN git checkout lww


# Automate `eval $(opam env)`

ENTRYPOINT ["opam", "exec", "--"]
CMD ["/bin/bash", "--login"]
